cuahang = ["T-Shirt","Sweater"]
print("Welcome t’o our shop, what do you want (C, R, U, D)? C")
item = input("Enter new item :")
cuahang.append(item)
print("Our items :",cuahang)
print("")
print("Welcome to our shop, what do you want (C, R, U, D)? R")
print("Our items :",cuahang)
print("")
print("Welcome to our shop, what do you want (C, R, U, D)? U")
print("Update position? 1")
item2 = input("Enter new item :")
cuahang[1] = item2
print("Our items:",cuahang)
print("")
print("Welcome to our shop, what do you want (C, R, U, D)? D")
item3 = input("Delete item? :")
cuahang.remove(item3)
print("Our items:",cuahang)
